_format_version: "2.1"
_transform: true

services:
  - name: example-service
    url: https://mockbin.org
    plugins:
      - name: validation
    routes:
      - name: jspath
        paths:
          - /test
  - name: usertest-service
    url: http://192.168.1.207:7879
    routes:
      - name: route-test
        paths:
          - /user/api
